#!/bin/bash -e
# Copyright 2018 Paul Brewer, Economic and Financial Technology Consulting LLC
# This consolidates a collection of csv files in subdirectories ./A ./B ./C ...
# to a ./consolidated subdirectory.  The csvs are appended in order.
# The header in ./A is kept but ignored in subsequent csvs.
# The script is intentionally single-threaded to avoid storage contention.
FIRSTDIR=./A
DESTDIR=./consolidated
CASEDIRS=[A-Z]
CSVS=$(cd $FIRSTDIR; echo *csv)
mkdir -p $DESTDIR
for csv in $CSVS
do (
    head -1 $FIRSTDIR/$csv > $DESTDIR/$csv
    for dir in $CASEDIRS;
    do
	tail -n "+2" $dir/$csv >> $DESTDIR/$csv
    done
)
done

